### ISSUE TITLE
Relax NG Schema

### ISSUE THREAD

**Issue by dotfig** [Samantha-Mcguigan/newsAnalysis#6]
Do you guys think that we should have four schemas? Meaning that we would have one schema for each news site(CNN, Fox, NPR, BBC) considering they are all going to have different format.

**Comment by ebeshero** [comment]
@ajnewton1 Would the differences in format actually affect the way you're coding the articles? One reason to have a unified schema is to make it possible to study and extract data from the texts in the same way...

**Comment by ebeshero** [comment]
@ajnewton1 @Samantha-Mcguigan @jonhoranic @RJP43  "Houston, we have a problem!" I'm reviewing your project files, and while you have a well documented Relax NG schema, that schema has not been associated with the code in your project GitHub. When I go to associate it there are lots and lots of validation errors. 

Now that you've all been learning a lot about how to write code to process information from markup, I am sure you all definitely realize why it's important that all of your XML files be encoded in a clear and consistent way, so you can write code to reach into all the files and grab the information you need. Everyone needs to get back into this code, associate your project schema, and make sure your XML files all follow your team plan. That might involve making some late-breaking changes to the schema, too, but from what I can see that schema looks mostly reasonable. If you notice it not permitting things you want to do (like place `<emo>` tags in the title elements, then you want to modify the schema to permit that, and make sure everyone knows what you're doing.

**Comment by ebeshero** [comment]
@jonhoranic @ajnewton1 @Samantha-Mcguigan @RJP43 
As I'm reviewing your project schema, I noticed some things that you might want to fine-tune:
* First, you might want to be making more use of datatypes for some of your elements/attributes. Specifically, I'd suggest you want to set **xsd:anyURI** as a datatype value for the element content of `<hyperlink>` and the attribute content of `@href`, since that datatype is distinct for an absolute URL (`http://address`) and will help ensure you're not missing something there.

* I'm a little worried about the schema's positioning of some of elements that look (in most of the files) like they'd usually appear near the top. These include the self-closing `<media/>` element, which is flagging as an error in most of the coded files I'm looking at, and the `<subHead>` element. 
 --According to your schema, `<media>` is supposed to be a child of the `<body>`, but in most of your files it is sitting between the `<head>` and the `<body>`, and because you're all using it as a self-closing element, there's something Very Invalid going on:
Your schema mandates quite clearly that `<article>` (your root element) is supposed to ONLY contain element content (not text). I think that's a good idea, since we can expect the root element to contain the major elements that define the organization of your documents. However, when people are placing the self-closing `<media/>` element in between the `<head>` and the `<body>` that is not only invalid placement, but it's forcing text to be a child of `<article>`--probably not what we want! 
**My suggestion:** `<media>` might well NOT be part of the body of an article and you may not want to include it there, but if you move it up, I'd either put it inside `<head>` or in between `<head>` and `<body>` (as an element child of `<article>`, and I'd permit it to include text content. I'm not sure I understand why you're treating it as a self-closing element, so maybe I'm missing something. Anyway, this is a pretty frequently flagged problem across your project files when I go to associate your schema. 

* Really pay attention to the structure of the documents. Sometimes you have content that appears outside paragraphs. (So sometimes we end a paragraph and see an `<a href="...">...</a>` as a *sibling* element to a paragraph followed by text, when we really should not be seeing text as a child of `<body>` or a sibling of a `<p>`, right? 
* I've added some [more information and examples of datatypes](http://newtfire.org/dh/explainRNG.html#datatypes) to our [Relax NG tutorial](http://newtfire.org/dh/explainRNG.html), and it's probably a good idea to review that as we're returning to work on your project. 

* `<emo>` element: Should it be allowed to appear in `<title>` elements? (Maybe it should, but then you want to review all the titles across the collection and make sure it appears regularly. And remember, you'll want this to be `mixed{}` syntax so it can float anywhere in relation to text.) 

* I don't think it's going to be terribly difficult to repair your code, but it is **absolutely necessary** that you associate your XML with your project schema **ASAP** so that you can correct this problems and make sure everyone is coding consistently. That is the foundation you'll need for pulling information that you can visualize to answer your project's research question! 

* One of you (it doesn't matter who) should step up **today** and associate that schema line with each of your files, and as you code new files, **make sure that schema line is associated at the top**, and push that back to the team repository. Changes to the schema should all be implemented ASAP, too.

* Can you work out amongst yourselves a plan to review and correct the XML files (and alter the schema as you go)? 

Thanks, everyone. I know this sounds a little dire, and I also know that each of you is a strong and capable coder, so I know you'll make the effort to get this right. :-)

**Comment by Samantha-Mcguigan** [comment]
@ebeshero I'm not sure what it means to to set `xsd:anyURI` as a datatype value.  Should it be like this:
`<xsdid>http://www.bbc.com/news/election-us-2016-37920175</xsdid>`
that doesn't seem right.

**Comment by ebeshero** [comment]
@Samantha-Mcguigan That's something we'd do inside the schema, and it's similar to setting the format for an ISO date value as the contents of an element or an attribute. You have two places in your project code where you want to include a website address: they are:
1) a `<hyperlink>` element, and
2) the `@href` on `<a>`
In the Relax-NG file, you can control the contents of each of these to make them always be a standard website address, by setting the content of each to be in the format `xsd:anyURI`. Does that make sense?

**Comment by ebeshero** [comment]
@Samantha-Mcguigan I think I see what's throwing you off: the examples I link to are Relax-NG in XML syntax, not the syntax we're using in our schema. Here's a better example. What we're doing is like this:
````
when = attribute when {xsd:date | xsd:gYearMonth | xsd:gYear} 
````
and would look like this:
````
hyperlink = element hyperlink {xsd:anyURI}
````

**Comment by Samantha-Mcguigan** [comment]
That makes so much more sense!! Thank you!
________________________________
